### ISSUE TITLE
An error has occured - very long ime to submit an error.

### ISSUE THREAD

**Issue by TimVanhamme** [ethz-spylab/satml-llms-ctf-issues#49] opened 2024-01-31 18:10 UTC
While submitting messages to the llama model an error occurs. Below the error message from the json response. It happens consitently for all llama models. Suddenly it takes very long to get a single response.

What is weird is that despite querying a llama model the error message refers to the OpenAI API

{'detail': ['OpenAI API error: A timeout error occurred. The function call took longer than 60 second(s).. If you have a team budget,note that your team budget has NOT been consumed.']}

**Comment by dedeswim** [comment] 2024-01-31 20:22
Hi! We are using a library for which the same exceptions are thrown no matter if they are from issues with Together or OpenAI APIs. Looks like Together was having some issues, but it seems to be fine now as I can't reproduce your error anymore. I'm going to close this issue tomorrow unless the error comes up again

**Closed** 2024-01-31 22:53 UTC
